/*
 * Small, platform-independent KSP player for testing generated archives.
 * SDL2 supplies the audio device on macOS, Linux, and Windows; libkss supplies
 * the KSS emulator and this program only connects the two.
 */

#include <errno.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(_WIN32)
#include <conio.h>
#else
#include <fcntl.h>
#include <termios.h>
#include <unistd.h>
#endif

#if defined(__clang__)
/* libkss and SDL2 both expose legacy Uint8/Uint32 typedefs. */
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wtypedef-redefinition"
#pragma clang diagnostic ignored "-Wstrict-prototypes"
#endif
#include <SDL.h>
#include "kss/kss.h"
#include "kssplay.h"
#include "ksp/ksp.h"
#include "zx_decompressor.h"
#ifdef KSS_HAVE_MOONSOUND
#include "moonsound_opl4.h"
#endif
#if defined(__clang__)
#pragma clang diagnostic pop
#endif

#define DEFAULT_RATE 44100
#define DEFAULT_CHANNELS 1
#define DEFAULT_SECONDS 60
#define DEFAULT_FADE_SECONDS 5
#define MAX_RATE 384000
#define MAX_SECONDS 3600

typedef struct {
  const char *input;
  int song;
  int rate;
  int channels;
  int seconds;
  int fade_seconds;
  int loops;
  int quality;
  int info_only;
  int mapper_base;
  int mapper_base_set;
  const char *opl4_rom;
  const char *mwk_path;
} Options;

typedef struct {
  int is_ksp;
  KSP_INDEX index;
  struct KCPRuntime *kcp;
} KSPResources;

typedef struct {
  KSSPLAY *player;
  struct KCPRuntime *kcp;
  uint32_t rate;
  uint8_t channels;
  uint64_t total_frames;
  uint64_t rendered_frames;
  uint64_t auto_end_frames;
  int auto_advance;
  int fade_seconds;
  int loops;
  int fade_started;
  SDL_atomic_t done;
} AudioState;

typedef struct {
  int active;
  int escape_state;
  int escape_waits;
#if !defined(_WIN32)
  int original_flags;
  struct termios original_settings;
#endif
} TerminalState;

typedef enum {
  TERMINAL_NONE = 0,
  TERMINAL_QUIT,
  TERMINAL_PREVIOUS,
  TERMINAL_NEXT
} TerminalAction;

static volatile sig_atomic_t stop_requested;

#ifdef KSS_HAVE_MOONSOUND
#ifndef KSP_DEFAULT_YRW801_ROM
#define KSP_DEFAULT_YRW801_ROM ""
#endif

static int readable_file(const char *path) {
  FILE *file;

  if (!path || !path[0]) {
    return 0;
  }
  file = fopen(path, "rb");
  if (!file) {
    return 0;
  }
  fclose(file);
  return 1;
}

static const char *find_default_opl4_rom(const KSPResources *resources) {
  static const char *const environment_names[] = {
      "KSP_YRW801_ROM", "YRW801_ROM"};
  static const char *const local_names[] = {"yrw801.rom", "YRW801.ROM"};
  const char *path;
  size_t i;

  /* A plain KSS still behaves as before: enable MoonSound explicitly with
   * --opl4-rom. KSP containers generated by the MoonSound tools need it by
   * default, however, or their OPL4 channels are silently absent. */
  if (!resources || !resources->is_ksp) {
    return NULL;
  }

  for (i = 0; i < sizeof(environment_names) / sizeof(environment_names[0]);
       i++) {
    path = getenv(environment_names[i]);
    if (readable_file(path)) {
      return path;
    }
  }

  for (i = 0; i < sizeof(local_names) / sizeof(local_names[0]); i++) {
    if (readable_file(local_names[i])) {
      return local_names[i];
    }
  }

  if (readable_file(KSP_DEFAULT_YRW801_ROM)) {
    return KSP_DEFAULT_YRW801_ROM;
  }
  return NULL;
}
#endif

static void handle_interrupt(int signal_number) {
  (void)signal_number;
  stop_requested = 1;
}

static int terminal_prepare(TerminalState *terminal) {
  memset(terminal, 0, sizeof(*terminal));

#if defined(_WIN32)
  return 1;
#else
  {
    struct termios settings;

    if (!isatty(STDIN_FILENO)) {
      return 1;
    }
    if (tcgetattr(STDIN_FILENO, &terminal->original_settings) != 0) {
      return 0;
    }
    terminal->original_flags = fcntl(STDIN_FILENO, F_GETFL, 0);
    if (terminal->original_flags < 0) {
      return 0;
    }

    settings = terminal->original_settings;
    settings.c_lflag &= (tcflag_t) ~(ICANON | ECHO);
    settings.c_cc[VMIN] = 0;
    settings.c_cc[VTIME] = 0;
    if (tcsetattr(STDIN_FILENO, TCSANOW, &settings) != 0) {
      return 0;
    }
    if (fcntl(STDIN_FILENO, F_SETFL, terminal->original_flags | O_NONBLOCK) != 0) {
      tcsetattr(STDIN_FILENO, TCSANOW, &terminal->original_settings);
      return 0;
    }
    terminal->active = 1;
  }
  return 1;
#endif
}

static void terminal_restore(TerminalState *terminal) {
  if (!terminal->active) {
    return;
  }

#if defined(_WIN32)
  (void)terminal;
#else
  tcsetattr(STDIN_FILENO, TCSANOW, &terminal->original_settings);
  fcntl(STDIN_FILENO, F_SETFL, terminal->original_flags);
#endif
  terminal->active = 0;
}

static TerminalAction terminal_poll_action(TerminalState *terminal) {
#if defined(_WIN32)
  while (_kbhit()) {
    int key = _getch();
    if (key == 27) {
      return TERMINAL_QUIT;
    }
    if (key == 0 || key == 0xe0) {
      if (!_kbhit()) return TERMINAL_NONE;
      key = _getch();
      if (key == 75) return TERMINAL_PREVIOUS;
      if (key == 77) return TERMINAL_NEXT;
    }
  }
  return TERMINAL_NONE;
#else
  unsigned char input[32];
  ssize_t count;
  size_t i;

  if (!terminal->active) {
    return TERMINAL_NONE;
  }
  count = read(STDIN_FILENO, input, sizeof(input));
  if (count <= 0) {
    if (terminal->escape_state == 1 && ++terminal->escape_waits >= 2) {
      terminal->escape_state = 0;
      terminal->escape_waits = 0;
      return TERMINAL_QUIT;
    }
    return TERMINAL_NONE;
  }
  for (i = 0; i < (size_t)count; i++) {
    unsigned char key = input[i];
    terminal->escape_waits = 0;
    if (terminal->escape_state == 0) {
      if (key == 0x1b) terminal->escape_state = 1;
    } else if (terminal->escape_state == 1) {
      if (key == '[' || key == 'O') {
        terminal->escape_state = 2;
      } else {
        terminal->escape_state = 0;
        return TERMINAL_QUIT;
      }
    } else {
      terminal->escape_state = 0;
      if (key == 'C') return TERMINAL_NEXT;
      if (key == 'D') return TERMINAL_PREVIOUS;
    }
  }
  return TERMINAL_NONE;
#endif
}

static void usage(FILE *stream, const char *program) {
  fprintf(stream,
          "Usage: %s [options] FILE.KSP|FILE.KSS\n"
          "\n"
          "Play one KSP/KSS track through the default audio device.\n"
          "\n"
          "Options:\n"
          "  -sN, --song N       Song number (default: 0)\n"
          "  -pN, --seconds N    Play duration (default: 60)\n"
          "  -fN, --fade N       Fade duration in seconds (default: 5)\n"
          "  -lN, --loops N      Fade after this many loops (default: 1; 0=off)\n"
          "  -rN, --rate N       Requested sample rate (default: 44100)\n"
          "  -nN, --channels N   1 or 2 output channels (default: 1)\n"
          "  -qN, --quality N    0=low, 1=high (default: 1)\n"
          "  --mapper-base N    Map bank 0 to physical mapper segment N\n"
          "  --opl4-rom FILE     Use this YRW801 ROM for MoonSound\n"
          "  --mwk FILE          Override the embedded/external MWK samplepack\n"
          "                      (KSP files use their embedded MWK by default)\n"
          "  --info              Print archive metadata without playing\n"
          "  -h, --help          Show this help\n"
          "\n"
          "Short options accept either '-s3' or '-s 3'.\n",
          program);
}

static int parse_integer(const char *text, int minimum, int maximum, int *result) {
  char *end;
  long value;

  if (!text || !*text) {
    return 0;
  }

  errno = 0;
  value = strtol(text, &end, 10);
  if (errno == ERANGE || *end != '\0' || value < minimum || value > maximum) {
    return 0;
  }

  *result = (int)value;
  return 1;
}

static int take_short_value(int argc, char **argv, int *index,
                            const char *argument, const char **value) {
  if (argument[2] != '\0') {
    *value = argument + 2;
    return 1;
  }
  if (*index + 1 >= argc) {
    return 0;
  }
  *value = argv[++*index];
  return 1;
}

/* Returns 1 for a value, 0 for a missing value, and -1 when the option does
 * not match name. */
static int take_long_value(int argc, char **argv, int *index,
                           const char *argument, const char *name,
                           const char **value) {
  size_t length = strlen(name);

  if (strcmp(argument, name) == 0) {
    if (*index + 1 >= argc) {
      return 0;
    }
    *value = argv[++*index];
    return 1;
  }
  if (strncmp(argument, name, length) == 0 && argument[length] == '=') {
    *value = argument + length + 1;
    return (*value)[0] != '\0';
  }
  return -1;
}

static int set_option_value(char option, const char *value, Options *options) {
  switch (option) {
  case 's':
    if (!parse_integer(value, 0, 255, &options->song)) {
      fprintf(stderr, "error: invalid song number: %s\n", value);
      return 0;
    }
    break;
  case 'p':
    if (!parse_integer(value, 1, MAX_SECONDS, &options->seconds)) {
      fprintf(stderr, "error: invalid duration: %s\n", value);
      return 0;
    }
    break;
  case 'f':
    if (!parse_integer(value, 0, MAX_SECONDS, &options->fade_seconds)) {
      fprintf(stderr, "error: invalid fade duration: %s\n", value);
      return 0;
    }
    break;
  case 'l':
    if (!parse_integer(value, 0, 256, &options->loops)) {
      fprintf(stderr, "error: invalid loop count: %s\n", value);
      return 0;
    }
    break;
  case 'r':
    if (!parse_integer(value, 8000, MAX_RATE, &options->rate)) {
      fprintf(stderr, "error: invalid sample rate: %s\n", value);
      return 0;
    }
    break;
  case 'n':
    if (!parse_integer(value, 1, 2, &options->channels)) {
      fprintf(stderr, "error: channels must be 1 or 2\n");
      return 0;
    }
    break;
  case 'q':
    if (!parse_integer(value, 0, 1, &options->quality)) {
      fprintf(stderr, "error: quality must be 0 or 1\n");
      return 0;
    }
    break;
  default:
    fprintf(stderr, "error: unknown option: -%c\n", option);
    return 0;
  }
  return 1;
}

static int parse_options(int argc, char **argv, Options *options) {
  int i;

  memset(options, 0, sizeof(*options));
  options->rate = DEFAULT_RATE;
  options->channels = DEFAULT_CHANNELS;
  options->seconds = DEFAULT_SECONDS;
  options->fade_seconds = DEFAULT_FADE_SECONDS;
  options->loops = 1;
  options->quality = 1;

  for (i = 1; i < argc; i++) {
    const char *argument = argv[i];
    const char *value = NULL;
    int matched;

    if (argument[0] != '-' || strcmp(argument, "-") == 0) {
      if (options->input) {
        fprintf(stderr, "error: only one input file is supported\n");
        return 0;
      }
      options->input = argument;
      continue;
    }

    if (strcmp(argument, "-h") == 0 || strcmp(argument, "--help") == 0) {
      usage(stdout, argv[0]);
      exit(0);
    }
    if (strcmp(argument, "--info") == 0) {
      options->info_only = 1;
      continue;
    }
    if (strcmp(argument, "--opl4-rom") == 0) {
      if (++i >= argc || !argv[i][0]) {
        fprintf(stderr, "error: --opl4-rom needs a file\n");
        return 0;
      }
      options->opl4_rom = argv[i];
      continue;
    }
    if (strncmp(argument, "--opl4-rom=", 11) == 0) {
      if (!argument[11]) {
        fprintf(stderr, "error: --opl4-rom needs a file\n");
        return 0;
      }
      options->opl4_rom = argument + 11;
      continue;
    }
    if (strcmp(argument, "--mwk") == 0) {
      if (++i >= argc || !argv[i][0]) {
        fprintf(stderr, "error: --mwk needs a file\n");
        return 0;
      }
      options->mwk_path = argv[i];
      continue;
    }
    if (strcmp(argument, "--mapper-base") == 0) {
      if (++i >= argc || !parse_integer(argv[i], 0, 255,
                                        &options->mapper_base)) {
        fprintf(stderr, "error: --mapper-base needs a value from 0 to 255\n");
        return 0;
      }
      options->mapper_base_set = 1;
      continue;
    }
    if (strncmp(argument, "--mapper-base=", 14) == 0) {
      if (!parse_integer(argument + 14, 0, 255, &options->mapper_base)) {
        fprintf(stderr, "error: --mapper-base needs a value from 0 to 255\n");
        return 0;
      }
      options->mapper_base_set = 1;
      continue;
    }
    if (strncmp(argument, "--mwk=", 6) == 0) {
      if (!argument[6]) {
        fprintf(stderr, "error: --mwk needs a file\n");
        return 0;
      }
      options->mwk_path = argument + 6;
      continue;
    }

    if (argument[1] == '-') {
      const char *names[] = {"--song", "--seconds", "--fade", "--loops",
                             "--rate", "--channels", "--quality"};
      const char short_names[] = {'s', 'p', 'f', 'l', 'r', 'n', 'q'};
      size_t option_index;

      matched = -1;
      for (option_index = 0; option_index < sizeof(names) / sizeof(names[0]);
           option_index++) {
        matched = take_long_value(argc, argv, &i, argument,
                                  names[option_index], &value);
        if (matched != -1) {
          if (matched == 0) {
            fprintf(stderr, "error: %s needs a value\n", argument);
            return 0;
          }
          if (!set_option_value(short_names[option_index], value, options)) {
            return 0;
          }
          break;
        }
      }
      if (matched == -1) {
        fprintf(stderr, "error: unknown option: %s\n", argument);
        return 0;
      }
      continue;
    }

    if (argument[1] != 's' && argument[1] != 'p' && argument[1] != 'f' &&
        argument[1] != 'l' && argument[1] != 'r' && argument[1] != 'n' &&
        argument[1] != 'q') {
      fprintf(stderr, "error: unknown option: %s\n", argument);
      return 0;
    }
    if (!take_short_value(argc, argv, &i, argument, &value) ||
        !set_option_value(argument[1], value, options)) {
      if (!value) {
        fprintf(stderr, "error: option %s needs a value\n", argument);
      }
      return 0;
    }
  }

  if (!options->input) {
    fprintf(stderr, "error: no KSP/KSS input file specified\n");
    return 0;
  }
  if (options->fade_seconds > options->seconds) {
    options->fade_seconds = options->seconds;
  }
  return 1;
}

typedef struct KCPRuntime {
  int active;
  int applying;
  SDL_atomic_t failed;
  char format[5];
  uint8_t page_count;
  uint8_t track_count;
  uint8_t active_page;
  uint8_t song_id[256];
  uint8_t song_page[256];
  uint16_t load_address;
  uint16_t page_size;
  uint16_t overlay_address;
  uint8_t *pages;
  KSSPLAY *player;
} KCPRuntime;

#define KCP_FIXED_SIZE 528u
#define KCP_PAGE_BYTES 0x4000u
#define KCP_GATEWAY_ADDRESS 0xD8A0u
#define KCP_GATEWAY_MAILBOX 0xD89Fu

static uint16_t kcp_read_u16(const uint8_t *data) {
  return (uint16_t)data[0] | ((uint16_t)data[1] << 8);
}

static uint32_t kcp_read_u32(const uint8_t *data) {
  return (uint32_t)data[0] |
         ((uint32_t)data[1] << 8) |
         ((uint32_t)data[2] << 16) |
         ((uint32_t)data[3] << 24);
}

static int kcp_read_file(const char *path, uint8_t **data, size_t *size) {
  FILE *file;
  long length;
  uint8_t *buffer;

  *data = NULL;
  *size = 0;
  file = fopen(path, "rb");
  if (!file) {
    fprintf(stderr, "error: cannot open KSP/KSS file: %s\n", path);
    return 0;
  }
  if (fseek(file, 0, SEEK_END) != 0 || (length = ftell(file)) < 0 ||
      fseek(file, 0, SEEK_SET) != 0) {
    fprintf(stderr, "error: cannot determine file size: %s\n", path);
    fclose(file);
    return 0;
  }
  buffer = (uint8_t *)malloc(length ? (size_t)length : 1u);
  if (!buffer) {
    fprintf(stderr, "error: out of memory while reading %s\n", path);
    fclose(file);
    return 0;
  }
  if (length && fread(buffer, 1, (size_t)length, file) != (size_t)length) {
    fprintf(stderr, "error: cannot read KSP/KSS file: %s\n", path);
    free(buffer);
    fclose(file);
    return 0;
  }
  fclose(file);
  *data = buffer;
  *size = (size_t)length;
  return 1;
}

static void kcp_runtime_release(KCPRuntime *runtime) {
  if (!runtime) return;
  free(runtime->pages);
  memset(runtime, 0, sizeof(*runtime));
}

static int kcp_apply_sparse_overlay(uint8_t *page, uint32_t page_size,
                                    const uint8_t *overlay,
                                    uint32_t overlay_size) {
  uint32_t cursor = 0;

  while (cursor < overlay_size) {
    uint32_t offset;
    uint32_t length;
    if (overlay_size - cursor < 4u) return 0;
    offset = kcp_read_u16(overlay + cursor);
    length = kcp_read_u16(overlay + cursor + 2u);
    cursor += 4u;
    if (length > overlay_size - cursor || offset > page_size ||
        length > page_size - offset) {
      return 0;
    }
    memcpy(page + offset, overlay + cursor, length);
    cursor += length;
  }
  return 1;
}

static int kcp_runtime_load(const char *path, KCPRuntime *runtime) {
  uint8_t *file_data = NULL;
  uint8_t *template_page = NULL;
  uint8_t *overlay = NULL;
  const uint8_t *fixed;
  const uint8_t *kcp;
  size_t file_size = 0;
  size_t kcp_offset;
  size_t kcp_size;
  size_t cursor;
  uint32_t load_size;
  uint32_t page_count;
  uint32_t page_index;
  uint32_t page_size;
  uint32_t load_address;
  uint32_t overlay_address;
  int compressed;
  int result = -1;

  memset(runtime, 0, sizeof(*runtime));
  if (!kcp_read_file(path, &file_data, &file_size)) return -1;
  if (file_size < 0x20u ||
      (memcmp(file_data, "KSCC", 4) != 0 &&
       memcmp(file_data, "KSSX", 4) != 0)) {
    result = 0;
    goto cleanup;
  }

  load_size = kcp_read_u16(file_data + 6u);
  kcp_offset = 0x20u + (size_t)load_size;
  if (kcp_offset > file_size || file_size - kcp_offset < 4u) {
    result = 0;
    goto cleanup;
  }
  kcp = file_data + kcp_offset;
  compressed = memcmp(kcp, "KCPZ", 4) == 0;
  if (!compressed && memcmp(kcp, "KCPX", 4) != 0) {
    result = 0;
    goto cleanup;
  }
  kcp_size = file_size - kcp_offset;
  if (kcp_size < KCP_FIXED_SIZE) {
    fprintf(stderr, "error: truncated %.4s container in %s\n", kcp, path);
    goto cleanup;
  }

  fixed = kcp;
  page_count = fixed[5];
  load_address = kcp_read_u16(fixed + 8u);
  page_size = kcp_read_u16(fixed + 10u);
  overlay_address = kcp_read_u16(fixed + 12u);
  if (page_count == 0 || page_size != KCP_PAGE_BYTES ||
      load_address + page_size > 0x10000u ||
      overlay_address < load_address ||
      overlay_address > load_address + page_size) {
    fprintf(stderr, "error: unsupported %.4s page layout in %s\n",
            kcp, path);
    goto cleanup;
  }
  if ((!compressed && fixed[4] != 1u) ||
      (compressed && fixed[4] != 1u && fixed[4] != 2u)) {
    fprintf(stderr, "error: unsupported %.4s version %u in %s\n",
            kcp, fixed[4], path);
    goto cleanup;
  }
  if ((size_t)page_count > SIZE_MAX / page_size) {
    fprintf(stderr, "error: %.4s page table is too large\n", kcp);
    goto cleanup;
  }

  runtime->pages = (uint8_t *)malloc((size_t)page_count * page_size);
  template_page = (uint8_t *)malloc(page_size);
  if (!runtime->pages || !template_page) {
    fprintf(stderr, "error: out of memory loading %.4s pages\n", kcp);
    goto cleanup;
  }

  if (!compressed) {
    if (kcp_size < KCP_FIXED_SIZE + page_size) {
      fprintf(stderr, "error: truncated KCPX template in %s\n", path);
      goto cleanup;
    }
    memcpy(template_page, kcp + KCP_FIXED_SIZE, page_size);
    cursor = KCP_FIXED_SIZE + page_size;
    for (page_index = 0; page_index < page_count; page_index++) {
      uint32_t raw_size;
      uint8_t *page = runtime->pages + (size_t)page_index * page_size;
      if (cursor > kcp_size || kcp_size - cursor < 2u) {
        fprintf(stderr, "error: truncated KCPX page %u descriptor\n",
                page_index);
        goto cleanup;
      }
      raw_size = kcp_read_u16(kcp + cursor);
      cursor += 2u;
      if (raw_size > kcp_size - cursor) {
        fprintf(stderr, "error: truncated KCPX page %u overlay\n",
                page_index);
        goto cleanup;
      }
      memcpy(page, template_page, page_size);
      if (!kcp_apply_sparse_overlay(page, page_size,
                                    kcp + cursor, raw_size)) {
        fprintf(stderr, "error: invalid KCPX page %u overlay\n",
                page_index);
        goto cleanup;
      }
      cursor += raw_size;
    }
  } else {
    uint32_t version = fixed[4];
    uint32_t record_size = version == 2u ? 8u : 6u;
    uint32_t packed_template_size;
    uint32_t template_offset;

    if (kcp_size < KCP_FIXED_SIZE + 4u +
                   (size_t)page_count * record_size) {
      fprintf(stderr, "error: truncated KCPZ descriptor table in %s\n",
              path);
      goto cleanup;
    }
    packed_template_size = kcp_read_u16(kcp + KCP_FIXED_SIZE);
    template_offset = kcp_read_u16(kcp + KCP_FIXED_SIZE + 2u);
    if (template_offset > kcp_size ||
        packed_template_size > kcp_size - template_offset ||
        !zx0_decompress_data(kcp + template_offset,
                             packed_template_size,
                             template_page, page_size)) {
      fprintf(stderr, "error: cannot decode KCPZ template in %s\n",
              path);
      goto cleanup;
    }

    for (page_index = 0; page_index < page_count; page_index++) {
      size_t descriptor = KCP_FIXED_SIZE + 4u +
                          (size_t)page_index * record_size;
      uint32_t raw_size = kcp_read_u16(kcp + descriptor);
      uint32_t packed_size = kcp_read_u16(kcp + descriptor + 2u);
      uint32_t stream_offset = version == 2u
          ? kcp_read_u32(kcp + descriptor + 4u)
          : kcp_read_u16(kcp + descriptor + 4u);
      uint8_t *page = runtime->pages + (size_t)page_index * page_size;

      if (stream_offset > kcp_size || packed_size > kcp_size - stream_offset) {
        fprintf(stderr, "error: invalid KCPZ page %u stream\n",
                page_index);
        goto cleanup;
      }
      free(overlay);
      overlay = NULL;
      if (raw_size) {
        overlay = (uint8_t *)malloc(raw_size);
        if (!overlay ||
            !zx0_decompress_data(kcp + stream_offset, packed_size,
                                 overlay, raw_size)) {
          fprintf(stderr, "error: cannot decode KCPZ page %u\n",
                  page_index);
          goto cleanup;
        }
      } else if (packed_size != 0u) {
        fprintf(stderr, "error: invalid empty KCPZ page %u\n",
                page_index);
        goto cleanup;
      }
      memcpy(page, template_page, page_size);
      if (!kcp_apply_sparse_overlay(page, page_size, overlay, raw_size)) {
        fprintf(stderr, "error: invalid KCPZ page %u overlay\n",
                page_index);
        goto cleanup;
      }
    }
  }

  memcpy(runtime->format, kcp, 4);
  runtime->format[4] = '\0';
  runtime->page_count = (uint8_t)page_count;
  runtime->track_count = fixed[6];
  memcpy(runtime->song_id, fixed + 16u, sizeof(runtime->song_id));
  memcpy(runtime->song_page, fixed + 272u, sizeof(runtime->song_page));
  runtime->active_page = 0xffu;
  runtime->load_address = (uint16_t)load_address;
  runtime->page_size = (uint16_t)page_size;
  runtime->overlay_address = (uint16_t)overlay_address;
  runtime->active = 1;
  result = 1;

cleanup:
  free(overlay);
  free(template_page);
  free(file_data);
  if (result < 0) kcp_runtime_release(runtime);
  return result;
}

static void kcp_runtime_memwrite(void *context, uint32_t address,
                                 uint32_t data) {
  KCPRuntime *runtime = (KCPRuntime *)context;
  uint32_t begin;
  uint32_t end;
  uint32_t target;
  const uint8_t *page;

  if (!runtime || !runtime->active || runtime->applying ||
      address != KCP_GATEWAY_MAILBOX) {
    return;
  }
  if (data >= runtime->page_count || !runtime->player) {
    SDL_AtomicSet(&runtime->failed, 1);
    return;
  }

  begin = runtime->overlay_address;
  end = (uint32_t)runtime->load_address + runtime->page_size;
  page = runtime->pages + (size_t)data * runtime->page_size;
  runtime->applying = 1;
  for (target = begin; target < end; target++) {
    KSSPLAY_write_memory(runtime->player, target,
                         page[target - runtime->load_address]);
  }
  runtime->applying = 0;
  runtime->active_page = (uint8_t)data;
}

static uint32_t kcp_runtime_engine_song(const KCPRuntime *runtime,
                                        uint32_t public_song) {
  uint8_t song;

  if (!runtime || !runtime->active || public_song >= 256u)
    return public_song;
  song = runtime->song_id[public_song];
  return song == 0xffu ? 0u : song;
}

static int kcp_runtime_install(KCPRuntime *runtime, KSSPLAY *player,
                               uint32_t public_song) {
  static const uint8_t gateway[] = {
      0x32, (uint8_t)(KCP_GATEWAY_MAILBOX & 0xffu),
      (uint8_t)(KCP_GATEWAY_MAILBOX >> 8), 0xc9
  }; /* LD (D89FH),A / RET */
  uint32_t index;
  uint32_t page_index;
  const uint8_t *page;

  if (!runtime || !runtime->active || !player) return 1;
  if (public_song >= 256u ||
      (page_index = runtime->song_page[public_song]) >= runtime->page_count) {
    fprintf(stderr, "error: KCP song %u has no valid page mapping\n",
            public_song);
    return 0;
  }
  runtime->player = player;
  SDL_AtomicSet(&runtime->failed, 0);
  runtime->applying = 1;
  page = runtime->pages + (size_t)page_index * runtime->page_size;
  for (index = 0; index < runtime->page_size; index++) {
    KSSPLAY_write_memory(player, runtime->load_address + index, page[index]);
  }
  for (index = 0; index < sizeof(gateway); index++) {
    KSSPLAY_write_memory(player, KCP_GATEWAY_ADDRESS + index,
                         gateway[index]);
  }
  runtime->applying = 0;
  runtime->active_page = (uint8_t)page_index;
  KSSPLAY_set_memwrite_handler(player, runtime, kcp_runtime_memwrite);
  return 1;
}

static int load_ksp_resources(const char *path, KSPResources *resources) {
  char error[256];
  int kcp_result;

  memset(resources, 0, sizeof(*resources));
  resources->kcp = (KCPRuntime *)calloc(1, sizeof(KCPRuntime));
  if (!resources->kcp) {
    fprintf(stderr, "error: out of memory allocating KCP runtime\n");
    return -1;
  }
  kcp_result = kcp_runtime_load(path, resources->kcp);
  if (kcp_result < 0) return -1;
  if (!ksp_validate_file(path, 1, &resources->index, error, sizeof(error))) {
    /* Ordinary KSS files do not have a KSP trailer. */
    return 0;
  }
  resources->is_ksp = 1;
  return 1;
}

static const KSP_ENTRY *ksp_song_entry(const KSPResources *resources,
                                       uint32_t song) {
  uint32_t i;
  if (!resources) return NULL;
  for (i = 0; i < resources->index.entry_count; i++) {
    const KSP_ENTRY *entry = &resources->index.entries[i];
    if (entry->id == song && !strcmp(entry->type, "SONG")) return entry;
  }
  return NULL;
}

static int adjacent_song(const KSPResources *resources, const KSS *kss,
                         int current, int direction, int *result) {
  if (resources && resources->kcp && resources->kcp->active) {
    int last = (int)resources->kcp->track_count - 1;
    if ((direction > 0 && current >= last) ||
        (direction < 0 && current <= 0))
      return 0;
    *result = current + direction;
    return 1;
  }
  if (resources && resources->is_ksp &&
      ksp_index_is_compact(&resources->index)) {
    uint32_t i;
    int found = 0;
    int candidate = direction > 0 ? 256 : -1;
    for (i = 0; i < resources->index.entry_count; i++) {
      const KSP_ENTRY *entry = &resources->index.entries[i];
      int id;
      if (strcmp(entry->type, "SONG")) continue;
      id = (int)entry->id;
      if ((direction > 0 && id > current && id < candidate) ||
          (direction < 0 && id < current && id > candidate)) {
        candidate = id;
        found = 1;
      }
    }
    if (!found) return 0;
    *result = candidate;
    return 1;
  }

  if ((direction > 0 && current >= kss->trk_max) ||
      (direction < 0 && current <= kss->trk_min))
    return 0;
  *result = current + direction;
  return 1;
}

static const KSSINFO *track_info(const KSS *kss, int song) {
  uint32_t i;

  if (!kss || !kss->info) return NULL;
  for (i = 0; i < kss->info_num; i++) {
    if (kss->info[i].song == song) return &kss->info[i];
  }
  return NULL;
}

static const char *ksp_song_title(const Options *options,
                                  const KSPResources *resources, int song) {
  static char title[51];
  const KSP_ENTRY *entry;
  uint8_t *data = NULL;
  char error[128];
  size_t length;

  if (!options || !resources || !resources->is_ksp ||
      !ksp_index_is_compact(&resources->index))
    return NULL;
  entry = ksp_song_entry(resources, (uint32_t)song);
  if (!entry || !ksp_read_chunk(options->input, entry, &data, error,
                                sizeof(error)) || entry->unpacked_size <= 0xE2u) {
    free(data);
    return NULL;
  }
  length = entry->unpacked_size - 0xE2u;
  if (length > 50u) length = 50u;
  memcpy(title, data + 0xE2u, length);
  free(data);
  title[length] = '\0';
  while (length > 0 && (title[length - 1] == ' ' || title[length - 1] == '\t'))
    title[--length] = '\0';
  return title[0] ? title : NULL;
}

static void print_playing_message(const Options *options,
                                  const KSPResources *resources,
                                  const KSS *kss, int song, uint32_t rate,
                                  uint8_t channels, const char *driver) {
  const KSSINFO *info = track_info(kss, song);
  const char *title = info && info->title[0]
                          ? info->title
                          : (kss && kss->title[0] ? (const char *)kss->title
                                                   : ksp_song_title(options,
                                                                    resources,
                                                                    song));

  if (title) {
    fprintf(stderr, "playing %d - %s at %u Hz, %u channel(s) via %s\n",
            song, title, rate, channels, driver ? driver : "SDL audio");
  } else {
    fprintf(stderr, "playing song %d at %u Hz, %u channel(s) via %s\n",
            song, rate, channels, driver ? driver : "SDL audio");
  }
}

static void set_track_duration(AudioState *state, const KSS *kss, int song,
                               int requested_seconds) {
  const KSSINFO *info = track_info(kss, song);
  uint64_t requested_frames = (uint64_t)state->rate *
                              (uint64_t)requested_seconds;

  state->total_frames = requested_frames;
  state->auto_end_frames = 0;
  state->auto_advance = 1;
  if (info && info->time_in_ms > 0) {
    state->auto_end_frames = ((uint64_t)info->time_in_ms * state->rate) / 1000u;
    if (state->auto_end_frames > requested_frames)
      state->auto_end_frames = 0;
  }
}

static void configure_player_output(KSSPLAY *player, const Options *options,
                                    uint8_t channels) {
  KSSPLAY_set_device_quality(player, KSS_DEVICE_PSG,
                             (uint32_t)options->quality);
  KSSPLAY_set_device_quality(player, KSS_DEVICE_SCC,
                             (uint32_t)options->quality);
  KSSPLAY_set_device_quality(player, KSS_DEVICE_OPLL,
                             (uint32_t)options->quality);
  if (channels == 2) {
    KSSPLAY_set_device_pan(player, KSS_DEVICE_PSG, -32);
    KSSPLAY_set_device_pan(player, KSS_DEVICE_SCC, 32);
    player->opll_stereo = 1;
    KSSPLAY_set_channel_pan(player, KSS_DEVICE_OPLL, 0, 1);
    KSSPLAY_set_channel_pan(player, KSS_DEVICE_OPLL, 1, 2);
    KSSPLAY_set_channel_pan(player, KSS_DEVICE_OPLL, 2, 1);
    KSSPLAY_set_channel_pan(player, KSS_DEVICE_OPLL, 3, 2);
    KSSPLAY_set_channel_pan(player, KSS_DEVICE_OPLL, 4, 1);
    KSSPLAY_set_channel_pan(player, KSS_DEVICE_OPLL, 5, 2);
  }
}

static KSS *materialize_compact_song(const Options *options,
                                     const KSPResources *resources,
                                     uint32_t song) {
  uint8_t *image = NULL;
  uint32_t size = 0;
  KSS *kss;
  char error[256];

  if (!ksp_build_kss_image_for_song(options->input, &resources->index, song,
                                    &image, &size, error, sizeof(error))) {
    fprintf(stderr, "error: cannot materialize compact KSP song %u: %s\n",
            song, error);
    return NULL;
  }
  kss = KSS_bin2kss(image, size, options->input);
  free(image);
  if (!kss)
    fprintf(stderr, "error: compact KSP song %u is not a valid image\n", song);
  return kss;
}

#ifdef KSS_HAVE_MOONSOUND
static int load_embedded_mwk(const Options *options,
                             const KSPResources *resources,
                             KSS_MOONSOUND *moonsound, uint32_t song) {
  const KSP_ENTRY *song_entry;
  const KSP_ENTRY *mwk_entry = NULL;
  uint8_t *mwk_data = NULL;
  uint32_t mwk_id, i;
  char error[256];

  if (options->mwk_path || !resources || !resources->is_ksp || !moonsound)
    return 1;
  song_entry = ksp_song_entry(resources, song);
  mwk_id = song_entry ? song_entry->aux : song;
  for (i = 0; i < resources->index.entry_count; i++) {
    const KSP_ENTRY *entry = &resources->index.entries[i];
    if (entry->id == mwk_id && !strcmp(entry->type, "MWK ")) {
      mwk_entry = entry;
      break;
    }
  }
  if (!mwk_entry) return 1;
  if (!ksp_read_chunk(options->input, mwk_entry, &mwk_data, error,
                      sizeof(error)) ||
      !kss_moonsound_load_mwk_data(moonsound, mwk_data,
                                   mwk_entry->unpacked_size, error,
                                   sizeof(error))) {
    free(mwk_data);
    fprintf(stderr, "error: embedded MWK could not be loaded: %s\n", error);
    return 0;
  }
  free(mwk_data);
  return 1;
}
#endif

static void release_ksp_resources(KSPResources *resources) {
  if (!resources)
    return;
  if (resources->is_ksp)
    ksp_free_index(&resources->index);
  if (resources->kcp) {
    kcp_runtime_release(resources->kcp);
    free(resources->kcp);
    resources->kcp = NULL;
  }
  memset(resources, 0, sizeof(*resources));
}

static void print_info(const KSS *kss, const KSPResources *resources) {
  if (resources && resources->kcp && resources->kcp->active) {
    printf("container: %s\n", resources->kcp->format);
    printf("KCP pages: %u (%u public tracks)\n",
           resources->kcp->page_count, resources->kcp->track_count);
    printf("runtime overlay: $%04X-$%04X\n",
           resources->kcp->overlay_address,
           (unsigned)(resources->kcp->load_address + resources->kcp->page_size - 1u));
  } else if (resources && resources->is_ksp) {
    printf("container: KSP1\n");
    printf("KSP chunks: %u\n", resources->index.entry_count);
    {
      uint32_t i, song_count = 0, mwk_count = 0;
      for (i = 0; i < resources->index.entry_count; i++) {
        if (!strcmp(resources->index.entries[i].type, "SONG")) song_count++;
        if (!strcmp(resources->index.entries[i].type, "MWK ")) mwk_count++;
      }
      printf("embedded resources: %u SONG(s), %u MWK(s)\n", song_count,
             mwk_count);
    }
  } else {
    printf("container: KSS\n");
  }
  printf("id: %.8s\n", kss->idstr);
  printf("title: %.*s\n", KSS_TITLE_MAX, kss->title);
  printf("format: %s\n", kss->kssx ? "KSSX" : "KSCC");
  printf("load: $%04X-$%04X\n", kss->load_adr,
         (unsigned)(kss->load_adr + kss->load_len - 1));
  printf("init: $%04X\n", kss->init_adr);
  printf("play: $%04X\n", kss->play_adr);
  printf("banks: %u (%s)\n", kss->bank_num,
         kss->bank_mode == KSS_8K ? "8K" : "16K");
  if (resources && resources->kcp && resources->kcp->active) {
    printf("songs: 0-%u\n", (unsigned)resources->kcp->track_count - 1u);
  } else {
    printf("songs: %u-%u\n", kss->trk_min, kss->trk_max);
  }
  printf("info records: %u\n", kss->info_num);
}

static void audio_callback(void *userdata, Uint8 *stream, int length) {
  AudioState *state = (AudioState *)userdata;
  const int bytes_per_frame = state->channels * (int)sizeof(int16_t);
  int frames;
  uint64_t remaining;

  SDL_memset(stream, 0, (size_t)length);
  if (SDL_AtomicGet(&state->done) || length < bytes_per_frame) {
    return;
  }

  remaining = state->total_frames - state->rendered_frames;
  frames = length / bytes_per_frame;
  if ((uint64_t)frames > remaining) {
    frames = (int)remaining;
  }
  if (frames <= 0) {
    SDL_AtomicSet(&state->done, 1);
    return;
  }

  KSSPLAY_calc(state->player, (int16_t *)stream, (uint32_t)frames);
  if (state->kcp && SDL_AtomicGet(&state->kcp->failed)) {
    SDL_AtomicSet(&state->done, 1);
    return;
  }
  state->rendered_frames += (uint64_t)frames;

  if (!state->fade_started && state->fade_seconds > 0) {
    uint64_t fade_frames = (uint64_t)state->fade_seconds * state->rate;
    int loop_reached = state->loops > 0 &&
                       KSSPLAY_get_loop_count(state->player) >= state->loops;
    int time_reached = state->rendered_frames + fade_frames >= state->total_frames;

    if (loop_reached || time_reached) {
      KSSPLAY_fade_start(state->player,
                         (uint32_t)state->fade_seconds * 1000u);
      state->fade_started = 1;
    }
  }

  if (state->rendered_frames >= state->total_frames) {
    SDL_AtomicSet(&state->done, 1);
  } else if (state->auto_advance && state->auto_end_frames > 0 &&
             state->rendered_frames >= state->auto_end_frames) {
    SDL_AtomicSet(&state->done, 1);
  } else if (state->auto_advance && state->auto_end_frames == 0 &&
             state->rendered_frames >= (uint64_t)state->rate * 5u &&
             KSSPLAY_get_stop_flag(state->player)) {
    SDL_AtomicSet(&state->done, 1);
  }
}

static int play_audio(const Options *options, KSS **kss_pointer,
                      KSPResources *resources) {
  SDL_AudioSpec desired;
  SDL_AudioSpec actual;
  SDL_AudioDeviceID device = 0;
  AudioState state;
  TerminalState terminal;
  const char *driver;
  KSS *kss = *kss_pointer;
  int current_song = options->song;
  int result = 0;
#ifdef KSS_HAVE_MOONSOUND
  KSS_MOONSOUND *moonsound = NULL;
  const char *opl4_rom = options->opl4_rom;
#endif

  memset(&state, 0, sizeof(state));
  memset(&terminal, 0, sizeof(terminal));
  SDL_AtomicSet(&state.done, 0);

  if (SDL_Init(SDL_INIT_AUDIO) != 0) {
    fprintf(stderr, "error: SDL audio initialization failed: %s\n",
            SDL_GetError());
    return 0;
  }

  SDL_zero(desired);
  desired.freq = options->rate;
  desired.format = AUDIO_S16SYS;
  desired.channels = (Uint8)options->channels;
  desired.samples = 1024;
  desired.callback = audio_callback;
  desired.userdata = &state;

  device = SDL_OpenAudioDevice(NULL, 0, &desired, &actual,
                               SDL_AUDIO_ALLOW_FREQUENCY_CHANGE |
                                   SDL_AUDIO_ALLOW_CHANNELS_CHANGE);
  if (!device) {
    fprintf(stderr, "error: cannot open an audio device: %s\n", SDL_GetError());
    SDL_QuitSubSystem(SDL_INIT_AUDIO);
    return 0;
  }
  if (actual.format != AUDIO_S16SYS || actual.channels < 1 || actual.channels > 2) {
    fprintf(stderr, "error: audio device did not accept 16-bit mono/stereo PCM\n");
    goto cleanup;
  }

  state.rate = (uint32_t)actual.freq;
  state.channels = actual.channels;
  state.fade_seconds = options->fade_seconds;
  state.loops = options->loops;
  state.kcp = resources && resources->kcp && resources->kcp->active
      ? resources->kcp : NULL;
  set_track_duration(&state, kss, current_song, options->seconds);
  state.player = KSSPLAY_new(state.rate, state.channels, 16);
  if (!state.player) {
    fprintf(stderr, "error: could not create KSS player\n");
    goto cleanup;
  }
#ifdef KSS_HAVE_MOONSOUND
  if (!opl4_rom) {
    opl4_rom = find_default_opl4_rom(resources);
  }
  if (resources && resources->is_ksp && !opl4_rom) {
    fprintf(stderr,
            "error: no YRW801 ROM found for this KSP file; use "
            "--opl4-rom FILE or set KSP_YRW801_ROM\n");
    goto cleanup;
  }
  if (options->mwk_path && !opl4_rom) {
    fprintf(stderr, "error: --mwk requires a YRW801 ROM\n");
    goto cleanup;
  }
  if (opl4_rom) {
    char error[256];
    moonsound = kss_moonsound_create(opl4_rom, state.rate, error,
                                     sizeof(error));
    if (!moonsound) {
      fprintf(stderr, "error: %s\n", error);
      goto cleanup;
    }
    if (options->mwk_path &&
        !kss_moonsound_load_mwk(moonsound, options->mwk_path, error,
                                sizeof(error))) {
      fprintf(stderr, "error: %s\n", error);
      goto cleanup;
    }
    if (!load_embedded_mwk(options, resources, moonsound,
                           (uint32_t)current_song))
      goto cleanup;
    KSSPLAY_set_moonsound(state.player, moonsound);
    fprintf(stderr, "MoonSound: using YRW801 ROM %s\n", opl4_rom);
  }
#else
  if (resources && resources->is_ksp) {
    fprintf(stderr,
            "error: this KSP file requires a MoonSound-enabled build; "
            "configure with -DKSP_MOONSOUND_DIR=...\n");
    goto cleanup;
  }
  if (options->opl4_rom) {
    fprintf(stderr, "error: this build has no MoonSound backend; configure with -DKSP_MOONSOUND_DIR=...\n");
    goto cleanup;
  }
  if (options->mwk_path) {
    fprintf(stderr, "error: --mwk requires a MoonSound-enabled build\n");
    goto cleanup;
  }
#endif
  if (KSSPLAY_set_data(state.player, kss) != 0) {
    fprintf(stderr, "error: could not attach KSP/KSS playback data\n");
    goto cleanup;
  }
  if (options->mapper_base_set)
    KSSPLAY_set_mapper_base(state.player, (uint32_t)options->mapper_base);
  KSSPLAY_reset(state.player,
                kcp_runtime_engine_song(state.kcp,
                                        (uint32_t)current_song),
                0);
  if (!kcp_runtime_install(state.kcp, state.player,
                           (uint32_t)current_song))
    goto cleanup;
  KSSPLAY_set_device_quality(state.player, KSS_DEVICE_PSG,
                             (uint32_t)options->quality);
  KSSPLAY_set_device_quality(state.player, KSS_DEVICE_SCC,
                             (uint32_t)options->quality);
  KSSPLAY_set_device_quality(state.player, KSS_DEVICE_OPLL,
                             (uint32_t)options->quality);
  if (state.channels == 2) {
    KSSPLAY_set_device_pan(state.player, KSS_DEVICE_PSG, -32);
    KSSPLAY_set_device_pan(state.player, KSS_DEVICE_SCC, 32);
    state.player->opll_stereo = 1;
    KSSPLAY_set_channel_pan(state.player, KSS_DEVICE_OPLL, 0, 1);
    KSSPLAY_set_channel_pan(state.player, KSS_DEVICE_OPLL, 1, 2);
    KSSPLAY_set_channel_pan(state.player, KSS_DEVICE_OPLL, 2, 1);
    KSSPLAY_set_channel_pan(state.player, KSS_DEVICE_OPLL, 3, 2);
    KSSPLAY_set_channel_pan(state.player, KSS_DEVICE_OPLL, 4, 1);
    KSSPLAY_set_channel_pan(state.player, KSS_DEVICE_OPLL, 5, 2);
  }

  driver = SDL_GetCurrentAudioDriver();
  print_playing_message(options, resources, kss, current_song, state.rate,
                        state.channels, driver);
  if (!terminal_prepare(&terminal)) {
    fprintf(stderr, "warning: Escape key handling is unavailable on this terminal\n");
  }
  fprintf(stderr,
          "press Left/Right for previous/next; Escape or Ctrl-C to stop\n");

  SDL_PauseAudioDevice(device, 0);
  while (!stop_requested) {
    TerminalAction action = terminal_poll_action(&terminal);
    int automatic_next = 0;

    if (state.kcp && SDL_AtomicGet(&state.kcp->failed)) {
      fprintf(stderr, "error: invalid internal KCP page request\n");
      break;
    }
    if (SDL_AtomicGet(&state.done)) {
      if (state.auto_advance) {
        action = TERMINAL_NEXT;
        automatic_next = 1;
      } else {
        break;
      }
    }
    if (action == TERMINAL_QUIT) {
      SDL_AtomicSet(&state.done, 1);
      break;
    } else if (action == TERMINAL_PREVIOUS || action == TERMINAL_NEXT) {
      int next_song;
      int direction = action == TERMINAL_NEXT ? 1 : -1;
      if (!adjacent_song(resources, kss, current_song, direction,
                         &next_song)) {
        if (automatic_next) {
          break;
        }
        fprintf(stderr, "no %s song\n", direction > 0 ? "next" : "previous");
      } else {
        int compact = resources && resources->is_ksp &&
                      ksp_index_is_compact(&resources->index);
        KSS *next_kss = compact
                            ? materialize_compact_song(options, resources,
                                                       (uint32_t)next_song)
                            : kss;
        int attached = next_kss != NULL;
        KSSPLAY *old_player = NULL;
        if (attached) {
          /* Stop callbacks while replacing the emulation image. This is
           * important for compact MoonSound songs: reset changes both the
           * KSS memory map and the shared OPL4 state. */
          SDL_PauseAudioDevice(device, 1);
          SDL_LockAudioDevice(device);
#ifdef KSS_HAVE_MOONSOUND
          if (compact && !load_embedded_mwk(options, resources, moonsound,
                                            (uint32_t)next_song))
            attached = 0;
#endif
          {
            int replace_player = compact;
#ifdef KSS_HAVE_MOONSOUND
            replace_player = compact && moonsound == NULL;
#endif
            if (replace_player) {
              KSSPLAY *replacement = KSSPLAY_new(state.rate, state.channels, 16);
              if (!replacement || KSSPLAY_set_data(replacement, next_kss) != 0) {
                KSSPLAY_delete(replacement);
                fprintf(stderr,
                        "error: could not attach KSS playback data for song %d\n",
                        next_song);
                attached = 0;
              } else {
                if (options->mapper_base_set)
                  KSSPLAY_set_mapper_base(replacement,
                                          (uint32_t)options->mapper_base);
                KSSPLAY_reset(replacement,
                              kcp_runtime_engine_song(state.kcp,
                                                      (uint32_t)next_song),
                              0);
                if (!kcp_runtime_install(state.kcp, replacement,
                                         (uint32_t)next_song)) {
                  KSSPLAY_delete(replacement);
                  attached = 0;
                  replacement = NULL;
                }
                if (replacement) {
                  configure_player_output(replacement, options,
                                          state.channels);
                  old_player = state.player;
                  state.player = replacement;
                }
              }
            } else if (compact &&
                       KSSPLAY_set_data(state.player, next_kss) != 0) {
              fprintf(stderr,
                      "error: could not attach KSP/KSS playback data for song %d\n",
                      next_song);
              attached = 0;
            }
          }
          if (attached) {
              if (old_player == NULL) {
                if (options->mapper_base_set)
                  KSSPLAY_set_mapper_base(state.player,
                                          (uint32_t)options->mapper_base);
                KSSPLAY_reset(state.player,
                              kcp_runtime_engine_song(state.kcp,
                                                      (uint32_t)next_song),
                              0);
                if (!kcp_runtime_install(state.kcp, state.player,
                                         (uint32_t)next_song))
                  attached = 0;
              }
            if (attached) {
              set_track_duration(&state, next_kss, next_song,
                                 options->seconds);
              state.rendered_frames = 0;
              state.fade_started = 0;
              SDL_AtomicSet(&state.done, 0);
            }
          }
          SDL_UnlockAudioDevice(device);
          SDL_PauseAudioDevice(device, 0);
          KSSPLAY_delete(old_player);
        }
        if (attached) {
          if (compact) {
            KSS_delete(kss);
            kss = next_kss;
            *kss_pointer = kss;
          }
          current_song = next_song;
          print_playing_message(options, resources, kss, current_song,
                                state.rate, state.channels, driver);
        } else if (compact && next_kss) {
          KSS_delete(next_kss);
        }
      }
    }
    SDL_Delay(25);
  }
  SDL_PauseAudioDevice(device, 1);
  result = !(state.kcp && SDL_AtomicGet(&state.kcp->failed));

cleanup:
  terminal_restore(&terminal);
  if (state.kcp && state.player) {
    KSSPLAY_set_memwrite_handler(state.player, NULL, NULL);
    state.kcp->player = NULL;
  }
  if (device) {
    SDL_CloseAudioDevice(device);
  }
  KSSPLAY_delete(state.player);
#ifdef KSS_HAVE_MOONSOUND
  kss_moonsound_delete(moonsound);
#endif
  SDL_QuitSubSystem(SDL_INIT_AUDIO);
  return result;
}

int main(int argc, char **argv) {
  Options options;
  KSS *kss;
  KSPResources resources;
  int ksp_result;
  int result;
  void (*previous_interrupt_handler)(int);

  if (!parse_options(argc, argv, &options)) {
    usage(stderr, argv[0]);
    return 2;
  }

  ksp_result = load_ksp_resources(options.input, &resources);
  if (ksp_result < 0)
    return 1;

  if (resources.is_ksp && ksp_index_is_compact(&resources.index)) {
    kss = materialize_compact_song(&options, &resources,
                                   (uint32_t)options.song);
  } else {
    kss = KSS_load_file((char *)options.input);
  }
  if (!kss) {
    fprintf(stderr, "error: cannot load KSP/KSS file: %s\n", options.input);
    release_ksp_resources(&resources);
    return 1;
  }

  if ((resources.kcp && resources.kcp->active &&
       (options.song < 0 || options.song >= resources.kcp->track_count)) ||
      ((!resources.kcp || !resources.kcp->active) &&
       (options.song < kss->trk_min || options.song > kss->trk_max))) {
    unsigned maximum = resources.kcp && resources.kcp->active
                           ? (unsigned)resources.kcp->track_count - 1u
                           : kss->trk_max;
    fprintf(stderr, "error: song %d is outside archive range %u-%u\n",
            options.song,
            resources.kcp && resources.kcp->active ? 0u : kss->trk_min,
            maximum);
    KSS_delete(kss);
    release_ksp_resources(&resources);
    return 1;
  }

  if (options.info_only) {
    print_info(kss, &resources);
    KSS_delete(kss);
    release_ksp_resources(&resources);
    return 0;
  }

  stop_requested = 0;
  previous_interrupt_handler = signal(SIGINT, handle_interrupt);
  if (previous_interrupt_handler == SIG_ERR) {
    fprintf(stderr, "warning: Ctrl-C handling is unavailable\n");
    result = play_audio(&options, &kss, &resources) ? 0 : 1;
  } else {
    result = play_audio(&options, &kss, &resources) ? 0 : 1;
    signal(SIGINT, previous_interrupt_handler);
  }
  KSS_delete(kss);
  release_ksp_resources(&resources);
  return result;
}
